; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 %s -o - | FileCheck %s

; The nonzero case shrinks from 10 to 9 instructions.

declare i32 @llvm.ctlz.i32(i32, i1 immarg)

define i32 @ctlz_ashr_nonzero(i32 %x, i32 %amount, i32 %salt, i32 %bias) {
; CHECK-LABEL: ctlz_ashr_nonzero:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_xad_u32 v0, v0, v2, v3
; CHECK-NEXT:    v_mul_lo_u32 v0, v0, 3
; CHECK-NEXT:    v_bfrev_b32_e32 v2, -2
; CHECK-NEXT:    v_bfrev_b32_e32 v3, 1
; CHECK-NEXT:    v_and_or_b32 v0, v0, v2, v3
; CHECK-NEXT:    v_ashrrev_i32_e32 v0, v1, v0
; CHECK-NEXT:    v_ffbh_u32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %mixed = xor i32 %x, %salt
  %offset = add i32 %mixed, %bias
  %product = mul i32 %offset, 3
  %masked = and i32 %product, 2147483647
  %src = or i32 %masked, -2147483648
  %shr = ashr i32 %src, %amount
  %ctlz = call i32 @llvm.ctlz.i32(i32 %shr, i1 false)
  ret i32 %ctlz
}

define i32 @ctlz_ashr_may_zero(i32 %x, i32 %amount, i32 %salt, i32 %bias) {
; CHECK-LABEL: ctlz_ashr_may_zero:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_xad_u32 v0, v0, v2, v3
; CHECK-NEXT:    v_mul_lo_u32 v0, v0, 3
; CHECK-NEXT:    v_and_b32_e32 v0, 0x7fffffff, v0
; CHECK-NEXT:    v_ashrrev_i32_e32 v0, v1, v0
; CHECK-NEXT:    v_ffbh_u32_e32 v0, v0
; CHECK-NEXT:    v_min_u32_e32 v0, 32, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %mixed = xor i32 %x, %salt
  %offset = add i32 %mixed, %bias
  %product = mul i32 %offset, 3
  %masked = and i32 %product, 2147483647
  %shr = ashr i32 %masked, %amount
  %ctlz = call i32 @llvm.ctlz.i32(i32 %shr, i1 false)
  ret i32 %ctlz
}
