; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 %s -o - | FileCheck %s

; The nonzero case shrinks from 5 to 4 instructions.

declare i32 @llvm.ctlz.i32(i32, i1 immarg)
declare i32 @llvm.smax.i32(i32, i32)

define i32 @ctlz_smax_nonzero(i32 %x) {
; CHECK-LABEL: ctlz_smax_nonzero:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_max_i32_e32 v0, 1, v0
; CHECK-NEXT:    v_ffbh_u32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %max = call i32 @llvm.smax.i32(i32 %x, i32 1)
  %ctlz = call i32 @llvm.ctlz.i32(i32 %max, i1 false)
  ret i32 %ctlz
}

define i32 @ctlz_smax_may_zero(i32 %x, i32 %y) {
; CHECK-LABEL: ctlz_smax_may_zero:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_max_i32_e32 v0, v0, v1
; CHECK-NEXT:    v_ffbh_u32_e32 v0, v0
; CHECK-NEXT:    v_min_u32_e32 v0, 32, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ctlz = call i32 @llvm.ctlz.i32(i32 %max, i1 false)
  ret i32 %ctlz
}
