; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 %s -o - | FileCheck %s

; The nonzero case shrinks from 10 to 9 instructions.

declare i32 @llvm.ctlz.i32(i32, i1 immarg)

define i32 @ctlz_lshr_nonzero(i32 %x, i32 %amount, i32 %salt) {
; CHECK-LABEL: ctlz_lshr_nonzero:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_xor_b32_e32 v0, v0, v2
; CHECK-NEXT:    v_mad_u64_u32 v[3:4], s[4:5], v0, 3, v[1:2]
; CHECK-NEXT:    v_and_b32_e32 v1, 7, v1
; CHECK-NEXT:    v_xor_b32_e32 v0, v3, v2
; CHECK-NEXT:    v_or_b32_e32 v0, 0x80, v0
; CHECK-NEXT:    v_lshrrev_b32_e32 v0, v1, v0
; CHECK-NEXT:    v_ffbh_u32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %mixed = xor i32 %x, %salt
  %product = mul i32 %mixed, 3
  %offset = add i32 %product, %amount
  %remixed = xor i32 %offset, %salt
  %src = or i32 %remixed, 128
  %bounded = and i32 %amount, 7
  %shr = lshr i32 %src, %bounded
  %ctlz = call i32 @llvm.ctlz.i32(i32 %shr, i1 false)
  ret i32 %ctlz
}

define i32 @ctlz_lshr_may_zero(i32 %x, i32 %amount, i32 %salt) {
; CHECK-LABEL: ctlz_lshr_may_zero:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_xor_b32_e32 v0, v0, v2
; CHECK-NEXT:    v_mad_u64_u32 v[3:4], s[4:5], v0, 3, v[1:2]
; CHECK-NEXT:    v_and_b32_e32 v1, 15, v1
; CHECK-NEXT:    v_xor_b32_e32 v0, v3, v2
; CHECK-NEXT:    v_or_b32_e32 v0, 0x80, v0
; CHECK-NEXT:    v_lshrrev_b32_e32 v0, v1, v0
; CHECK-NEXT:    v_ffbh_u32_e32 v0, v0
; CHECK-NEXT:    v_min_u32_e32 v0, 32, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %mixed = xor i32 %x, %salt
  %product = mul i32 %mixed, 3
  %offset = add i32 %product, %amount
  %remixed = xor i32 %offset, %salt
  %src = or i32 %remixed, 128
  %bounded = and i32 %amount, 15
  %shr = lshr i32 %src, %bounded
  %ctlz = call i32 @llvm.ctlz.i32(i32 %shr, i1 false)
  ret i32 %ctlz
}
